<div class="index">
<a href="location.php?num=1">1</a>
<a href="location.php?num=2">2</a>
3
<a href="location.php?num=4">4</a>
</div>
<div class="text">
<h3>Historical Places</h3>
<img class='right' src="../Common CSS/santhome.jpg" />
<h4>Churches</h4>


<h5>Basilica of the National Shrine of St.Thomas</h5>
Basilica of the National Shrine of St.Thomas, Santhome High Rd. In the whole world, there are only three churches built over the tomb of an Apostle of Jesus Christ- the Basilica of Saint Peter built over the tomb of St.Peter in Rome, Cathedral of Santiago de Compostela built over the tomb of St.James in Spain and Basilica of the National Shrine of St.Thomas built over the tomb of St.Thomas. Basilica of the National Shrine of St.Thomas is in Chennai, India. The present National Shrine of St.Thomas is built over the tomb of Saint Thomas the Apostle, who came to India in the year 52 AD. After preaching on the West coast, he came to Chennai (formerly Madras), and suffered martyrdom on a hill at the outskirts of the city, today known as "St. Thomas Mount." His body was buried on the spot over which the present Basilica stands. The shrine was restored in 2004. A valuable work of art kept in the Basilica is an ancient painting of Our Blessed Mother, in front of which the other great apostle of India, St. Francis Xavier, used to pray. There are two new structures today: The Tomb Chapel below the Basilica and Museum cum theatre. The new underground chapel with a separate access outside the church structure, allows pilgrims to pray at the tomb and tourists to visit it, without disturbing the sacred functions in the church. The museum exhibits artifacts connected with St. Thomas and the Basilica, and the theatre is used for screening a short video on the life of the Apostle. 5:AM-9PM daily. +91 44 24985455, +91 44 24980758. Email: parishpriest@santhomechurch.com Website: www.santhomechurch.com


<h5>St. Mary's Church</h5>
St. Mary's Church, situated in the fort, is one of the oldest surviving churches built by the British in India. This is the first English church in India and the oldest Anglican church in the East.Designed by William Dixon, the then Master Gunner of the Fort, it was constructed under the supervision of the Governor Streynsham Master. Given the precarious nature of the English presence in India at the time (not to mention later attacks by the French and the locals), the church has a defensive stance- thick walls, castellated parapets and a well within the grounds - to withstand any bombardment or siege). The church was consecrated on 28 October 1680. The tower was completed in 1701; the steeple added in 1710 and the tower was connected to the main body of the church in 1759. Robert Clive - more famous as Clive of India- married Margaret Maskelyne here in 1753. The first but equally famous wedding was that of Governor Elihu Yale (who was to become the benefactor of Yale College) to Catherine Himmers in November 1680. The interior of the church contains many fascinating plaques and monuments to early British India evoking past glories and lives full of achievement. It also contains the old colours of the Madras Fusiliers, the first European regiment of the East India Company. The glass windows, wall frescos, teak plaques still shine with their all time glory. 10AM-5PM daily except closed on F.



<h5>St. Thomas Mount</h5>
St. Thomas Mount St Thomas Mount, St Thomas Mount, Chennai South. St.Thomas, referred to as Didymus, in the Gospel of St.John is one of the twelve disciples of Jesus Christ. He is one of the prime witnesses to the resurrection of Jesus. St. Thomas Mount is associated with St. Thomas, the apostle of Christ, who is believed to have been martyred here. The mount is commonly called in Tamil "Parangi Malai" or "Bhringi Malai'.History says 2000 years ago, a saint 'Parangi' lived here ('parangi' in Tamil language is used to refer to a white person). According to local myth, St. Thomas was one of the first Christians to reach India and to preach Christianity. He is believed to have reached South India in AD 52, and spent the last years of his life in a cave on this hill. Tradition states that Thomas was assassinated by an arrow in AD 72, by persons hostile to him. Thus, the hillock acquired the name St. Thomas Mount. Over time Anglo-Indians predominated in this area. A small relic-filled Church built in 1523 by the Portuguese stands at the summit of the 300 feet high St. Thomas Mount. The place was visited by Pope John Paul II during his visit to India on 5 February 1986. At the northern foot of the mount, is a gateway of four impressive arches surmounted by a cross bearing the inscribed date 1547. A flight of 160 steps leads up to the summit of the mount. There are fourteen stations of the cross erected on the way to the summit.


<h4>Temples</h4>
<img class='left' src="../Common CSS/temple.jpg" />
<h5>Kapaleeswarar Temple</h5> (Kapaleeshwara), Mylapore, [23]. One of Chennai's oldest and best-known temples, said to date to the 8th century, although the present structure dates to the 1600s. Notable above all for its soaring, incredibly detailed 37m gopuram (entrance gate). There is a large water tank behind the temple, used for the Thaipusam festival (Jan-Feb), and plenty of flower shops all around. Within easy striking distance of the city centre.
<h5>The Parthasarathy Temple</h5> [24] at Tiruvallikkeni (Triplicane) as the Britishers called it, is considered be the oldest temple in the Chennai and origins date back to the 8th century AD, the reference of which has been made in the Vaishnavite works of the Alwar saints. The existence of the Tiruvallikkeni village in referred in the Pallava records and before. The temple derived its name from the pond in front of the temple. It was originally built by the Pallavas. The temple was renovated by later dynasties, the Chola and the Vijayanagar kingdom. The Temple is dedicated to Lord Krishna. The name Parthasarathy has been derived from two Sanskrit words Partha and Sarathy. The former word refers to Arjuna and the later means Charioteer. Its architecture is a combination of several temple building styles. There are inscriptions of the Pallavas, Cholas and the Vijayanagar kingdom on the temple structure. The temple besides being dedicated to Parthasarathy is also revered for Venkatakrishnaswami and to Ranganathar. The temple, when it was built, housed five avataras of the deity Vishnu. The structure, as it stands today, houses the shrines of popular deities like Venkatakrishnan with Rukmani, Balaraman, Satyaki, Anirudha, Pradyumna, Rama, Lakshmana, Barata, Sita, Shatrugna, Varadaraja and Hanuman.


<h5>Sri Ramakrishna Math- Universal Temple</h5>
Sri Ramakrishna_Math- Universal Temple [25], 31 Ramakrishna Math Rd, Mylapore. Swami Vivekananda on his return from the west was requested by the devotees in Madras (now Chennai) to start a Math here. To fulfill their desire Swamiji sent his brother-disciple Swami Ramakrishnananda to Madras in March 1897. After reaching Madras, the first thing Swami Ramakrishnananda did was to set up a small shrine for Sri Ramakrishna at a rented house. He lived there and led a life of renunciation, service and austerities. Slowly he built up the institution as the present Sri Ramakrishna Math and thus Sri Ramakrishna Math, Madras, came into existence. This is the oldest centre of the Ramakrishna Order in the South. Srimat Swami Bhuteshanandaji Maharaj, the 12th President of Ramakrishna Math and Ramakrishna Mission, laid the foundation-stone for this Universal Temple on 1 December 1994 in a grand function. It took five years for the project to take shape as the present grand Universal Temple. On 7 Feb 2000 the temple was dedicated by Srimat Swami Ranganathanandaji Maharaj, the 13th President of the Ramakrishna Order. Sri Ramakrishna Math completed hundred years of its service in 1997. The Math is regarded for its spiritual traditions, modern outlook, acceptance of all religions, service as the way of life. With its lushy green surroundings, the Universal Temple is the ideal spot for contemplation and meditation. 5AM-11:45AM and 3PM-9PM Tele: +91 044 2462110 Email: mail@chennaimath.org Web presence: www.chennaimath.org
<h4>Mosques</h4>


<h5>Big Mosque</h5>
Big Mosque also known as Wallajah Mosque, is situated at Walajah Road in Triplicane, Chennai is a historical landmark constructed by Wallajah family in memory of Nawab Muhammad Ali Walajah, in 1795. It is an imposing structure of symmetry and form of architectural magnificence with an imposing facade. The Mosque stands in extensive grounds, which are being used as a forum for religious and cultural activities. The magnificent grey granite structure is built without steel and wood. This architectural marvel is one of the important mosques in Chennai. The Nawab's descendants are still living in a mansion known as Amir Mahal. One distinctive feature of this mosque is that the chronogram engraved in stone and fixed on the inside of the western wall of the mosque is by a non-Muslim, Rajah Makkan Lal 'Khirad', a Persian and Arabic scholar of repute, who was the private secretary to the Nawab. It may be mentioned in this regard that, as far as is known, no other mosque in the world has a chronogram composed by a non-Muslim. The Mosque has two minarets at the front. Medieval architecture is clearly visible in the construction of this great mosque. The Eid Prayer timing remains the same, 10AM, since 1749 A.D. This historic mosque is under the management of H.H. Adjoining the Wallajah Mosque is the tomb of the great Islamic saint Maulana Abdul Ali Bahrul Uloom, a divine scholar of the days of the Nawab Wallajah. In this enclosure also are the tombs of the late Nawabs of the Carnatic, the Princess of Arcot and other eminent Muslim scholars and theologians. Wallajah Mosque can be reached either from Ellis Rd (backside) or the Triplicane High Rd.
</div>
<div class="index">
<a href="location.php?num=1">1</a>
<a href="location.php?num=2">2</a>
3
<a href="location.php?num=4">4</a>
</div>