<div class="index">
1
<a href="location.php?num=2">2</a>
<a href="location.php?num=3">3</a>
<a href="location.php?num=4">4</a>
</div>
<div class="text">
<h3>History</h3>
<img class='left' src="../Common CSS/ripon.jpg" />
Long the site of earlier coastal settlements, Madras was founded in 1639 when the British East India Company (represented by Francis Day and Andrew Cogan and aided by a local translator Beri Thimappa) was granted land to build a trading settlement by the local Telugu ruler (Nayak) of the suburb of Vandavasi, Damerla Venkatapathy Naidu on his father's name Damerla Chennappa Naidu. The document of the land grant is dated 22 August 1639, and hence Madras celebrates its birthday on 22 August each year as Madras day. Madras was one of the first outposts of British East India Company. Colonel William Lambton, superintendent of the great Trigonometrical Survey of India, started his journey of triangulating India from St. Thomas Mount. The British built Fort St. George (today the legislative and administrative
seat of the state). Fort St George was completed on St George's day in 1640 (23 April) and hence was named after the patron saint. George Town then developed becoming the modern city of Madras, absorbing several nearby boroughs. Thomas, one of the twelve apostles of Jesus Christ, is associated with Chennai. He is said to have come to India as an evangelist and died in what is now Chennai. Two suburbs, Santhome and St. Thomas Mount, are named in his memory.
In 1996, the Tamilnadu government renamed Madras to Chennai providing the reason that 'Chennai' was the city's traditional name while Madras was one derived during colonial rule.
Madras is derived from Madraspatnam, a name given to the area when the British negotiated settling there with Damerla Venkatapathy Nayakudu. The origin of the name is from Muthuraja Chennappa Nayakudu as Chennapatnam.Chennappa served under Sriranga Deva Raya assisting him against the Golkonda forces of Ibrahim Qutb Shah in several battles,notably in 1576 when Penukonda was captured by Ali Adil Shah and in 1579 when he captured the Golkonda Commander Murari Rao.
In 1580, Ibrahim Qutb Shah of Golkonda invaded Kondavidu. Later he took the Udayagiri Fort and began to massacre the locals. However he was defeated after a brief fight with the Raya's army. Qutb Shah later took the fort of Vinukonda. Sriranga defeated the Sultan's forces with the assistance of his generals muthuraja Chennappa[damarla was his surname] and Kasturiranga. During this fight, Chennappa lost his life. He was succeeded by Kasturiranga. When East India Company was established the St.George fort in the present day Chennai, for which the permission was granted by Damarla Venkatadri Nayakudu,the local palegar of that area ,under the condition that area is to be named in the honour of his father Muthuraja chennapa nayakudu as muthuraja chennapatanam.The East India Company in brief named
the area as madras[madras is a corrupt form of muthuraj].In earlier days this area was called as madraspattanam and also chennapatnam. Later Govt. of TAMILNADU,India renamed it as Chennai.
</div>

<div class='text'>
<h3>Culture</h3>
<img class='right' src="../Common CSS/Chennai Central.jpg" />
Chennai is gateway to the South, and its culture is distinctly different from that of any other city in India. Tamil tradition and culture is essentially the celebration of the beauty, which is exemplified through dance, clothing, and sculptures. Chennai is both an orthodox and a modern cosmopolitan city; the culture of the city reflects its diverse population. The traditional arts, music, dance and all other art forms of Tamilnadu grow and flourish here. The food is a unique blend of traditional, to fast foods and filter kaapi. It's a land of temples and priests. The architecture ranges from ancient temples to modern high-rises. Music is classical and western, to the growing nightlife in the city. You can find a school for traditional Bharatanatyam or Salsa dance and for music a veena / violin
or for Guitar/drums school in almost every neighborhood of the city. Chennai checks reflects its traditionalism every December when the music season is in full swing. Clothes are generally conservative but young people are contemporary.<br />
<h5>Traditional Tamil Clothing</h5> Tamil women traditionally wear the Saree or Sari while the men wear Dhoti, which could be either a white pancha or a colourful lungi with typical South Indian patterns. The sari, being an un-stitched wrap, enhances the shape of the wearer while only partially covering the midriff. In Indian philosophy, the navel of the Supreme Being is considered as the source of life and creativity. Therefore by tradition, the stomach and the navel is to be left unconcealed, though the philosophy behind the costume has largely been forgotten. This makes the realization of sharira-mandala (the body), where in Angikam bhuvanam yasya (the body is your world) unites with the shaarira-mandala (the whole universe), as expressed in the Natyashastra. These principles of the sari,
also hold for other forms of wraps, like the lungi or worn by men. The lungi can be wrapped over clockwise or anticlockwise and can be tied at the back or fixed just along the waist line. It's sometimes lifted till knee and tied at the waist leisurely or just held in hand to speed up walking. In tradition Brahmin homes men wear kachche panchey where it is tied at back by taking it between legs. Similar pattern is seen in women.<br />
<h5>Tamilnadu Cuisine</h5> Rice is the staple diet in Chennai, Dosa, Idli and Uttapam are popular in Chennai. The state of Tamilnadu has a distinct place in culinary map of the country. Chennai has a wide range of vegetarian and non-vegetarian delicacies to offer. The food here gets its flavor from a host of spices and condiments used in Tamil Nadu. Coconut, tamarind and asafetida are a must for almost all vegetarian recipes. Garam masala is avoided in Tamil cuisine. Refined gingelly oil is normally used as the medium of cooking. Chutneys and mixed spice are served in the lunch and enhance the taste of the meal. The Tamilnadu lunch or meals in Chennai consists of cooked rice served with different kinds of vegetable dishes, Sambar, chutneys, Rasam (a hot broth made with tamarind juice and pepper)
and curd (yogurt). The non-vegetarian lunch includes curries or dishes cooked with mutton, chicken or fish. Tamil meals are incomplete without crisp Papads or Appalam. In Chennai, Chettinad cuisine of Tamil Nadu is particularly famous. This cuisine is hot and spicy and provides delectable variety in mutton, chicken and fish dishes. Chettinad Pepper Chicken is one of the most famous dishes in Tamil Nadu. The Chennai style of Mughalai food can be tasted in the Biryani and Paya. Paya is a type of spiced trotter's broth and is eaten with either Parathas or Appam. Breakfast or tiffin in Chennai includes idly (steamed rice cakes), dosai (a pancake made from a batter of rice) and lentils crisp fried on a pan, vadai (deep fried doughnuts made from a batter of lentils), pongal (a mash of rice and lentils
boiled together and seasoned with ghee, cashew nuts, pepper and cummin seed), uppuma (cooked semolina seasoned in oil with mustard, pepper, cumin seed and dry lentils). Most of the breakfast dishes in Chennai are eaten with coconut chutney, sambar (seasoned lentil broth) and mulagai podi (a powdered mix of several dried lentils eaten with oil). Tamil Nadu, especially Chennai, is famous for its filter coffee. Most Tamils have a subtle disliking for instant coffee; therefore filter coffee is more popular. The preparation of filter coffee is almost like a daily chore, the coffee beans have to be first roasted and then ground. The coffee powder is then put into a filter set and hot boiled water is added to prepare the boiling and allowed to set for about 15 minutes. The decoction is then added
to milk with sugar to taste. The drink thus prepared is then poured from one container to another in rapid succession to make the perfect frothy cup of filter coffee. An exotic drink that refreshes you and the taste that lingers, served best in "Dabarah" set which includes a steel tumbler and saucer with a rim.<br />

</div>

<div class='text'>
<h5>Music</h5> 
<img class='left' src="../Common CSS/kabali.jpg" />There are many composers in Carnatic music. Purandara Dasa (1480-1564) is known as the father (Pitamaha) of Carnatic music due to his pioneering contributions to Carnatic music. Purandara Dasa is renowned for formulating the basic lessons of Carnatic music. The contemporaries Tyagaraja (1759-1847), Muthuswami Dikshitar, (1776-1827) and Syama Sastri (1762-1827), are regarded as the Trinity of Carnatic music due to the quality of Syama Sastri's compositions, the varieties of compositions of Muthuswami Dikshitar and Tyagaraja's prolific output in composing kritis. The compositions of these composers are rendered frequently by artists of today during the music festival season. Chennai Music Festival or December Season is a celebration of classical music and dance of South India held
during mid December to mid January in the capital city of Chennai, Tamil Nadu. The festival is held at a number of venues around the city by various 'sabhas' or organizations. Besides the auditoriums, well-known temple premises and heritage bungalows are being used as venues. The month long dance and music extravaganza will have performances of eminent artistes from various parts of India. The 'Margazhi festival of Dance and Music' started early back in 1927, to commemorate the anniversary of Madras Music Academy every December, was later adopted by various organizations which held art festivals in different parts of the city. The Tamil month of 'Margazhi' (December) is a sacred month of the Hindus. South Indian classical music (Carnatic Music) which has its roots in devotion to the gods, has
been a traditional form of worship from time immemorial. The city comes alive with the festival which has now developed into a cultural extravaganza with more than 2,000 artists participating in over 300 concerts. The festival also known as 'December Season' attracts expatriate Indians and scholars from around the world as well. Performances include Vocal and Instrumental music, Dance - solo and group, both by junior and senior artistes. Even upcoming artists get a chance to perform along with well-established artists. The music include classical vocal renditions in various South Indian languages like Tamil, Telugu and Kannada and instruments like Flute, Veena (a large string instrument), Goottuvadyam (similar to Veena but without frets), 'Nagaswaram' (pipe), 'Thavil' (percussion instrument),
'Mridangam' (drum), and even 'Ghatam' (a mud pot). The season goes on till mid January when the scene shifts to Tiruvaiyaru, near Tanjore, where 'Thyagaraja Aradhana' a week long music festival is held to celebrate the birth of one of the greatest Carnatic composers and one among the trinity of music - Thyagaraja. Information about the tickets and the venues can be had from the tourist office, Chennai. The weather is cool and pleasant at this time of the year. November- December is the best season to visit the city. Now the music in the motion picture industry has emerged as an important entertainment platform in Chennai, over the years portraying the cultural changes, trends, aspirations and developments experienced by its people.<br />
<h5>Dance</h5> Chennai is home to the distinct dance form- the Bharat Natyam. Bharatanatyam is the celebration of the eternal universe through the celebration of the beauty of the body. This is done through its tenets of having a perfectly erect posture, a straight and pout curving stomach, a well rounded and proportionate body mass- to the body structure, very long hair and curvaceous hips. These tenets bring to life the philosophy of Natyashastra, 'Angikam bhuvanam yasya' (The body is your world). This is elaborated in the araimandi posture, wherein the performer assumes a half sitting position with the knees turned sideways, with a very erect posture. In this fundamental posture of the Bharatanatyam dance, the distance between the head and the navel becomes equal to that between the earth
and the navel. In a similar way the distance between the outstretched right arm to the outstretched left arm becomes equal to the distance between the head and the feet, thus representing the "Natyapurusha", the embodiment of life and creation.<br />
</div>
<br />
<div class="index">
1
<a href="location.php?num=2">2</a>
<a href="location.php?num=3">3</a>
<a href="location.php?num=4">4</a>
</div>